services:
  go_db:
    container_name: go_db
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: adm
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d/

volumes:
  pgdata: {}