CREATE TABLE EMPLOYEE(
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	AGE INT NOT NULL,
	CEP VARCHAR(10) NOT NULL,
	GENDER VARCHAR(10),
	STREET VARCHAR(50),
	DISTRICT VARCHAR(50),
	CITY VARCHAR(50),
	STATE VARCHAR(50),
	NUMBER INT
);


INSERT INTO EMPLOYEE(NAME,AGE,CEP,GENDER,STREET,DISTRICT,CITY,STATE,NUMBER) VALUES ('Andrew Alves dos Santos',25,'06655110','Masculino','Rua Andradina','Jardim Santo Américo','Itapevi','SP',123)
INSERT INTO EMPLOYEE(NAME,AGE,CEP,GENDER,STREET,DISTRICT,CITY,STATE,NUMBER) VALUES ('Julia Sabrina Josefa Gonçalves',59,'07190913','Feminino','Rua Célia Domingues Faustino','Parque Cecap','Guarulhos','SP',330) 
INSERT INTO EMPLOYEE(NAME,AGE,CEP,GENDER,STREET,DISTRICT,CITY,STATE,NUMBER) VALUES ('Geraldo Julio Carlos Alves',35,'49061052','Masculino','Rua Esplanada','Santo Antônio','Aracaju','SE',104) 
INSERT INTO EMPLOYEE(NAME,AGE,CEP,GENDER,STREET,DISTRICT,CITY,STATE,NUMBER) VALUES ('Regina Sebastiana Allana Moraes',20,'69915120','Feminino','Travessa No Limite II','Conjunto Esperança','Rio Branco','AC',378)